import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "@/app/components/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <div className={'flex flex-row h-screen'}>
                    <div className={'w-1/12 min-w-max h-auto'}>
                        <Navbar/>
                    </div>
                    <div className={'w-11/12 h-auto'}>
                        <div className={'w-full flex flex-col'}>
                            <nav className={'w-full flex flex-row h-16 bg-cyan-400 items-center justify-between'}>
                                <p className={'p-4 text-xl font-bold'}>Vercel Admin</p>
                                <p className={'p-4 text-xl'}>kangminhyuk1111</p>
                            </nav>
                            {children}
                        </div>

                    </div>
                </div>
            </body>
        </html>
    )
}