import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "@/app/components/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <div className={'flex flex-row h-screen'}>
                    <div className={'w-1/12 min-w-max h-auto'}>
                        <Navbar/>
                    </div>
                    <div className={'w-11/12 h-auto'}>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}